services:
  dbms:
    image: postgres:16.1
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:5432

  back:
    image: localhost:5000/svqk/svqk-backend:0.8-SNAPSHOT
    environment:
      QUARKUS_DATASOURCE_USERNAME: ${DB_USER}
      QUARKUS_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbms:5432/postgres?currentSchema=public
      QUARKUS_HTTP_PORT: ${BACK_PORT}
      TZ: ${OS_TIMEZONE}
    ports:
      - ${BACK_PORT}:${BACK_PORT}

  migration:
    image: localhost:5000/svqk/svqk-migration:latest
    environment:
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_URL: jdbc:postgresql://dbms:5432/postgres?currentSchema=public
      TZ: ${OS_TIMEZONE}
    command: ["migrate", "info"]
    depends_on:
      dbms:
        condition: service_healthy
